// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4n56QGE14grlDGfisRoV0r531bLK6be0',
    appId: '1:277848116098:web:8dc580035c35d8b5259d9b',
    messagingSenderId: '277848116098',
    projectId: 'foodrecipesapp-2b0d2',
    authDomain: 'foodrecipesapp-2b0d2.firebaseapp.com',
    storageBucket: 'foodrecipesapp-2b0d2.firebasestorage.app',
    measurementId: 'G-N8DDWP34FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMiDTaWNlq5rhU51mtYzbSBb3ok8NZCUk',
    appId: '1:277848116098:android:a563aca6974c837f259d9b',
    messagingSenderId: '277848116098',
    projectId: 'foodrecipesapp-2b0d2',
    storageBucket: 'foodrecipesapp-2b0d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALenShAl0Tj2b1A0-u5mP-Uz-2Q_8uyCg',
    appId: '1:277848116098:ios:12569112265b471c259d9b',
    messagingSenderId: '277848116098',
    projectId: 'foodrecipesapp-2b0d2',
    storageBucket: 'foodrecipesapp-2b0d2.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALenShAl0Tj2b1A0-u5mP-Uz-2Q_8uyCg',
    appId: '1:277848116098:ios:12569112265b471c259d9b',
    messagingSenderId: '277848116098',
    projectId: 'foodrecipesapp-2b0d2',
    storageBucket: 'foodrecipesapp-2b0d2.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4n56QGE14grlDGfisRoV0r531bLK6be0',
    appId: '1:277848116098:web:cc34733ba5e76a61259d9b',
    messagingSenderId: '277848116098',
    projectId: 'foodrecipesapp-2b0d2',
    authDomain: 'foodrecipesapp-2b0d2.firebaseapp.com',
    storageBucket: 'foodrecipesapp-2b0d2.firebasestorage.app',
    measurementId: 'G-F06EPX4W2T',
  );
}
